---
language: node_js

node_js:
  - "0.12"

sudo: false

env:
  secure: "RyAVxLnM59XvrSz5ZoK/f2dtbLAkUnXH1RFyCzYFd61wrXPNhlqIrbxuw7K/xrw8EAGDuwwiaSzVhUYcBlEdaVdwZ24XC7h6Ro6Szcxk0HuQIctHFCm/8QJ41WqQdXWvkYHg8Yw9lCKfiNle5mkSvu0UH/8m6C3lBB8pxY4zziQ="

branches:
  except:
    - build

cache:
  directories:
    - node_modules

before_install:
  - openssl aes-256-cbc -K $encrypted_26acc1714b42_key -iv $encrypted_26acc1714b42_iv -in deploy.pem.enc -out deploy.pem -d
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm test

after_success:
  - ./build.sh
  - curl --data "build=true" -X POST $DOCKERTRIGGER
