language: node_js

node_js:
  - '0.12'

sudo: false

env:
  secure: RyAVxLnM59XvrSz5ZoK/f2dtbLAkUnXH1RFyCzYFd61wrXPNhlqIrbxuw7K/xrw8EAGDuwwiaSzVhUYcBlEdaVdwZ24XC7h6Ro6Szcxk0HuQIctHFCm/8QJ41WqQdXWvkYHg8Yw9lCKfiNle5mkSvu0UH/8m6C3lBB8pxY4zziQ=

cache:
  directories:
  - node_modules

before_install:
- openssl aes-256-cbc -K $encrypted_26acc1714b42_key -iv $encrypted_26acc1714b42_iv
  -in .travis/deploy.pem.enc -out .travis/deploy.pem -d
- npm config set spin false
- npm install -g npm@^2

install:
- npm install -g bower
- npm install
- bower install

script:
- npm test

before_deploy:
  - ./build.sh

deploy:
  provider: s3
  access_key_id: AKIAIQBWBNG4MO4YSSJA
  secret_access_key:
    secure: bmNf1UhAfBB2sK+sH+yZgWh4mAFOk3UwaCXTuG8/EgnN/E/zRaBGKGIKJb7XtAfP/OK+EMoKcoxRhssgNMGld+ZOIUnuzmKdnhp8w3d07flUrZCYsDEzedlrEoyf+CI7QNNLksBzKoOVt9YvSZGaR9Dz2diF3Gbn2v9Og54Z8sM=
  bucket: pebblescape
  local-dir: build
  upload-dir: dashboard
  acl: public_read
  skip_cleanup: true
  region: eu-west-1
  detect_encoding: true
  cache_control: "max-age=31536000"
  on:
    repo: pebblescape/dashboard

after_deploy:
  - curl --data "build=true" -X POST $DOCKERTRIGGER
